apiVersion: v1
kind: Service
metadata:
  name: recruiting-api-service
spec:
  selector:
    app: recruiting-api
  ports:
    - protocol: TCP
      port: 8089        
      targetPort: 8089  
  type: LoadBalancer 