// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	model "RECRUITING-API/internal/pkg/entity/model"

	schema "RECRUITING-API/internal/pkg/entity/schema"
)

// DBRepository is an autogenerated mock type for the DBRepository type
type DBRepository struct {
	mock.Mock
}

// CreateCandidate provides a mock function with given fields: ctx, request
func (_m *DBRepository) CreateCandidate(ctx *gin.Context, request *model.CreateCandidate) (int64, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateCandidate")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *model.CreateCandidate) (int64, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *model.CreateCandidate) int64); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *model.CreateCandidate) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCandidate provides a mock function with given fields: ctx, request
func (_m *DBRepository) DeleteCandidate(ctx *gin.Context, request *model.DeleteCandidate) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCandidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *model.DeleteCandidate) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectCandidate provides a mock function with given fields: ctx, request
func (_m *DBRepository) SelectCandidate(ctx *gin.Context, request *model.GetCandidate) (*schema.CandidatesGetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SelectCandidate")
	}

	var r0 *schema.CandidatesGetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *model.GetCandidate) (*schema.CandidatesGetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *model.GetCandidate) *schema.CandidatesGetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.CandidatesGetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *model.GetCandidate) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCandidate provides a mock function with given fields: ctx, request
func (_m *DBRepository) UpdateCandidate(ctx *gin.Context, request *model.UpdateCandidate) (*schema.CandidatesUpdateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCandidate")
	}

	var r0 *schema.CandidatesUpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *model.UpdateCandidate) (*schema.CandidatesUpdateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *model.UpdateCandidate) *schema.CandidatesUpdateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.CandidatesUpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *model.UpdateCandidate) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDBRepository creates a new instance of DBRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBRepository {
	mock := &DBRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
